### ISSUE TITLE
GP using ephemerals fails when using SCOOP

### ISSUE THREAD

**Issue by Anjum48** [DEAP/deap#108]
Hi,

When running https://github.com/DEAP/deap/blob/master/examples/gp/symbreg.py with SCOOP (with the `-m scoop` options), I seem to be getting this error in both Windows and Linux:

```
C:\Users\anjum\AppData\Local\Continuum\Anaconda3\python.exe -m scoop C:/Users/anjum/PycharmProjects/Testing/symbreg_scoop.py
[2015-11-26 14:50:20,324] launcher  INFO    SCOOP 0.7 1.1 on win32 using Python 3.4.3 |Anaconda 2.3.0 (64-bit)| (default, Nov  7 2015, 13:21:48) [MSC v.1600 64 bit (AMD64)], API: 1013
[2015-11-26 14:50:20,324] launcher  INFO    Deploying 24 worker(s) over 1 host(s).
[2015-11-26 14:50:20,324] launcher  INFO    Worker distribution: 
[2015-11-26 14:50:20,324] launcher  INFO       127.0.0.1:	23 + origin
Traceback (most recent call last):
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\site-packages\scoop\bootstrap\__main__.py", line 302, in <module>
    b.main()
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\site-packages\scoop\bootstrap\__main__.py", line 92, in main
    self.run()
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\site-packages\scoop\bootstrap\__main__.py", line 290, in run
    futures_startup()
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\site-packages\scoop\bootstrap\__main__.py", line 271, in futures_startup
    run_name="__main__"
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\site-packages\scoop\futures.py", line 64, in _startup
    result = _controller.switch(rootFuture, *args, **kargs)
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\site-packages\scoop\_control.py", line 253, in runController
    raise future.exceptionValue
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\site-packages\scoop\_control.py", line 127, in runFuture
    future.resultValue = future.callable(*future.args, **future.kargs)
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 240, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:/Users/anjum/PycharmProjects/Testing/symbreg_scoop.py", line 28, in <module>
    pset.addEphemeralConstant("rand101", lambda: random.randint(-1,1))
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\site-packages\deap\gp.py", line 451, in addEphemeralConstant
    PrimitiveSetTyped.addEphemeralConstant(self, name, ephemeral, __type__)
  File "C:\Users\anjum\AppData\Local\Continuum\Anaconda3\lib\site-packages\deap\gp.py", line 398, in addEphemeralConstant
    raise Exception("Ephemerals with different functions should "
Exception: Ephemerals with different functions should be named differently, even between psets.
[2015-11-26 14:50:30,086] launcher  (127.0.0.1:53644) INFO    Root process is done.
[2015-11-26 14:50:30,087] launcher  (127.0.0.1:53644) INFO    Finished cleaning spawned subprocesses.

Process finished with exit code 1
```
Any idea what the issue is?

Thanks for DEAP!
Anjum

**Comment by fmder** [comment]
Have you solved this issue?

Usually you should declare your ephemerals in the global scope of the main module. If it is done in a function that gets called more than one time you get this error.

**Comment by Anjum48** [comment]
The ephemerals in `symbreg.py` are declared in the global scope.

In the end I just used `multiprocessing` for my application, but it would be good to use SCOOP to scale up across machines.

**Comment by fmder** [comment]
@soravux @mgard any idea?

**Comment by mgard** [comment]
Well, it clearly relates on how SCOOP handles global constants. On the root worker, the code in the global scope seems to be executed twice: when Python parses the file and when SCOOP execute it. For most applications, this is not detrimental, but since GP stores its ephemeral at the module level, this leads to the creation of two identical ephemerals -- and thus the error.

One possible workaround for this bug (and the related warnings in #117 that are coming from the same source) is to actually test whether we are on the root worker or not, and execute the declarations only in the latter case. For instance, with symbreg example, replacing:
`pset.addEphemeralConstant("rand101", lambda: random.randint(-1,1))`
by
```
if not scoop.IS_ORIGIN:
    pset.addEphemeralConstant("rand101", lambda: random.randint(-1,1))
```
seems to solve the problem.

I agree that it is quite a nasty workaround, and it uses a constant that is marked as internal and "don't use in production" in SCOOP documentation : https://scoop.readthedocs.org/en/latest/api.html#scoop-constants-and-objects
However, I don't know enough about SCOOP internals to provide a better and more generic solution.  @soravux would be the one to ask, but I'm not sure he has plenty of time to work on scoop these days...

**Comment by soravux** [comment]
@mgard is spot on, it is due to the origin executing the script twice.
This particular bug was fixed in the development version of SCOOP. If you install the latest git version, you won't have this issue anymore, no hack needed. Bear in mind that the development version is not considered stable...

**Comment by fmder** [comment]
Thanks for chipping in @mgard and @soravux! I'll mark this and #117 as resolved.

**Comment by embg** [comment]
I concur with @soravux, installing from github instead of pip works for me.
