### ISSUE TITLE
AttributeError: 'set' object has no attribute 'sendResultBack'

### ISSUE THREAD

**Issue by embg** [DEAP/deap#144]
I ran DEAP overnight to try to get a good fit, but when I checked the next day I found that SCOOP had had an error after only a few generations. Something weird...

```
(pysr)emg3@647trc-lib0:~/pysr$ python -m scoop pysr.py
[2016-06-29 18:36:08,115] launcher  INFO    SCOOP 0.7 2.0 on linux using Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)], API: 1013
[2016-06-29 18:36:08,115] launcher  INFO    Deploying 4 worker(s) over 1 host(s).
[2016-06-29 18:36:08,115] launcher  INFO    Worker d--istribution: 
[2016-06-29 18:36:08,115] launcher  INFO       127.0.0.1:	3 + origin
Launching 4 worker(s) using /bin/bash.
Please wait, evaluating initial population...
gen	nevals	avg	std	min      	max         
0  	1000  	inf	inf	0.0194461	1.79769e+308
1  	500   	3.28878	5.04334	0.0194461	34.5157     
2  	500   	2.72468	2.98872	0.0194461	11          
3  	500   	2.76784	2.87041	0.010546 	11          
4  	500   	3.26026	3.47431	0.00982395	11          
5  	500   	4.28001	4.36229	0.00908401	13          
6  	500   	4.71493	4.75621	0.003721  	13          
7  	500   	5.48999	5.64341	0.00363013	21          
8  	500   	6.01841	6.16301	0.00363013	25          
9  	500   	5.73587	5.83848	0.00290756	19          
10 	500   	6.07772	6.30312	0.00121335	19          
11 	500   	7.4073 	7.71698	0.000811114	23          
12 	500   	8.33669	8.5421 	0.000668869	25          
13 	500   	9.47443	9.72786	0.000395687	33          
14 	500   	10.5743	10.9619	0.000395687	33          
Traceback (most recent call last):
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 298, in <module>
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 92, in main
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 285, in run
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 266, in futures_startup
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/futures.py", line 65, in _startup
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_control.py", line 258, in runController
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_types.py", line 352, in pop
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_types.py", line 375, in updateQueue
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_comm/scoopzmq.py", line 352, in recvFuture
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_comm/scoopzmq.py", line 253, in _recv
AttributeError: 'set' object has no attribute 'sendResultBack'
[2016-06-29 18:41:09,380] scoopzmq  (b'127.0.0.1:54109') ERROR   A worker exited unexpectedly. Read the worker logs for more information. SCOOP pool will now shutdown.
[2016-06-29 18:41:09,681] launcher  (127.0.0.1:37993) INFO    Root process is done.
[2016-06-29 18:41:09,681] launcher  (127.0.0.1:37993) INFO    Finished cleaning spawned subprocesses
```

**Comment by fmder** [comment]
This looks like a scoop error rather than deap.

2016-06-30 12:37 GMT-04:00 embg <notifications@github.com>:
