### ISSUE TITLE
TypeError: list indices must be integers or slices, not float

### ISSUE THREAD

**Issue by NightValbarz** [DEAP/deap#314]
Hello, am kinda new to using DEAP, i have been trying to use it for a keras model hyperparameter optimization, and i'm getting the previously marked error. 
What i'm generating is a list of numbers between 0 and 1.

Edit: Using python 3.6.4, deap 1.2.2

```

Traceback (most recent call last):
  File "/Users/Night/anaconda3/envs/env0/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-452b872916a8>", line 1, in <module>
    runfile('/Users/Night/Documents/Thesis-Experiment/LSTM-GA.py', wdir='/Users/Night/Documents/Thesis-Experiment')
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/Night/Documents/Thesis-Experiment/LSTM-GA.py", line 151, in <module>
    main()
  File "/Users/Night/Documents/Thesis-Experiment/LSTM-GA.py", line 144, in main
    halloffame=hof, verbose=True)
  File "/Users/Night/anaconda3/envs/env0/lib/python3.6/site-packages/deap/algorithms.py", line 318, in eaMuPlusLambda
    offspring = varOr(population, toolbox, lambda_, cxpb, mutpb)
  File "/Users/Night/anaconda3/envs/env0/lib/python3.6/site-packages/deap/algorithms.py", line 236, in varOr
    ind1, ind2 = toolbox.mate(ind1, ind2)
  File "/Users/Night/anaconda3/envs/env0/lib/python3.6/site-packages/deap/tools/crossover.py", line 109, in cxPartialyMatched
    p1[ind1[i]] = i
TypeError: list indices must be integers or slices, not float

```

Here is part of the code

```

creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, fitness=creator.FitnessMin)


toolbox = base.Toolbox()

toolbox.register("attr_float", random.random)
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr_float, n=10)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)



toolbox.register("evaluate", evaluation_fitness)
toolbox.register("mate", tools.cxPartialyMatched)
toolbox.register("mutate", tools.mutShuffleIndexes, indpb=0.2)
toolbox.register("select", tools.selTournament, tournsize=3)


def main(seed=13):
    random.seed(seed)
    pop = toolbox.population(n=POPULATION)
    hof = tools.HallOfFame(1)
    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("Avg", np.mean)
    stats.register("Std", np.std)
    stats.register("Min", np.min)
    stats.register("Max", np.max)

    algorithms.eaMuPlusLambda(pop, toolbox, cxpb=0.5, mutpb=0.2, mu=100, lambda_=200, ngen=GENERATIONS, stats=stats,
                              halloffame=hof, verbose=True)

    print(stats)
    return pop, stats, hof

```

**Comment by fmder** [comment]
Partially matched crossover is for permutation individuals only
