### ISSUE TITLE
bigfloat pickle

### ISSUE THREAD

**Issue by Ian-Re** [DEAP/deap#351]
hey everyone,

I'm still getting the hang of this and I can't seem to find help anywhere, so I thought I'd open an issue to get some help.

Here's my code:

```
import random
import array
from deap import base
from deap import tools
from deap import creator
from sympy.solvers import solve
from sympy import Symbol
from sympy import Eq
import bigfloat
import networkx
from sympy import exp
import matplotlib.pyplot as plt

# STEP 1 -> Defined constants
## number of individuals in the population
NP = 10
##coefficients from the datasheet of the PV panel
IscTempcoeff = 0.059
VocTempcoeff = -0.32
PeakPowTempcoeff = - 0.43
Voc = 45.79
Vmp = 36.38
Isc = 8.99
Imp = 8.52
Vt = 0.026
##amount of generations
max = 2
##lower and upper bounds of the variables to solve
Xih = [2, 1, 3000, 0.1, Isc]
Xil = [1, 0.1, 100, 0.000009, 0.1]


# crossover based on binomial
def cxBinomial(x, mutant, cr):
    size = len(x)
    index = random.randrange(size)
    for i in range(size):
        if i == index or random.random() < cr:
            x[i] = mutant[i]
    return x


# mutation function
def mutateDE(mutant, a, b, c, f):
    size = len(mutant)
    for i in range(size):
        mutant[i] = a[i] + f * (b[i] - c[i])
    return mutant


# Penalty function to ensure the parameters remain in acceptable range
def cxPenalty(x):
    z = random.uniform(0, 1)
    if (x[0] > Xih[0] or x[1] > Xih[1] or x[2] > Xih[2] or x[3] > Xih[3] or x[4] > Xih[4]):
        x[0] = x[0] - (z * (Xih[0] - Xil[0]))
        x[1] = x[1] - (z * (Xih[1] - Xil[1]))
        x[2] = x[2] - (z * (Xih[2] - Xil[2]))
        x[3] = x[3] - (z * (Xih[3] - Xil[3]))
        x[4] = x[4] - (z * (Xih[4] - Xil[4]))
    elif (x[0] < Xil[0] or x[1] < Xil[1] or x[2] < Xil[2] or x[3] < Xil[3] or x[4] < Xil[4]):
        x[0] = x[0] + (z * (Xih[0] - Xil[0]))
        x[1] = x[1] + (z * (Xih[1] - Xil[1]))
        x[2] = x[2] + (z * (Xih[2] - Xil[2]))
        x[3] = x[3] + (z * (Xih[3] - Xil[3]))
        x[4] = x[4] + (z * (Xih[4] - Xil[4]))

    return x


# evaluation and selection function
def eval(a, Rs, Rp, Io):
    r = (1 / (a * Vt))
    Gp = (1 / Rp)
    preex = round((r * (Vmp + (Imp * Rs))), 5)
    expo = bigfloat.exp(preex, bigfloat.precision(100))
    Jnum = ((Io) * (r) * expo - (Gp))
    Jden = (1 + ((Io) * (r) * (Rs) * expo) + (Gp * Rs))
    J = Jnum / Jden
    return J


def main():
    generation = 0

    creator.create("Fitnessmin", base.Fitness, weights=(-1.0,))
    creator.create("Individual", array.array, typecode='d', fitness=creator.Fitnessmin)
    toolbox = base.Toolbox()
    toolbox.register("attr_a", random.uniform, 1, 2)
    toolbox.register("attr_rs", random.uniform, 0.1, 1)
    toolbox.register("attr_rp", random.uniform, 100, 3000)
    toolbox.register("attr_io", random.uniform, 0.000009, 0.1)
    toolbox.register("attr_ipv", random.uniform, 0.1, Isc)
    toolbox.register("individual", tools.initCycle, creator.Individual,
                     (toolbox.attr_a, toolbox.attr_rs, toolbox.attr_rp, toolbox.attr_io, toolbox.attr_ipv), 1)
    toolbox.register("population", tools.initRepeat, list, toolbox.individual)
    toolbox.register("mutate", mutateDE, f=0.4)
    toolbox.register("select", tools.selRandom, k=3)
    toolbox.register("mate", cxBinomial, cr=0.4)
    toolbox.register("evaluate", eval)
    # STEP 2 - > generate population

    pop1 = toolbox.population(n=NP)
    # STEP 3 -> start the algorithm
    ## Hall of fame to save the best individual
    hof = tools.HallOfFame(1)

    while (generation < max):
        for agent in pop1:
            # Mutation
            a, b, c = [toolbox.clone(ind) for ind in toolbox.select(pop1)]
            mutant1 = toolbox.clone(agent)
            mutant = toolbox.clone(agent)
            mutant = toolbox.mutate(mutant, a, b, c)
            # crossover
            trialvec = toolbox.mate(mutant1, mutant)
            trialvec = cxPenalty(trialvec)
            trialeval = (toolbox.evaluate(trialvec[0], trialvec[1], trialvec[2], trialvec[3]))
            curreval = (toolbox.evaluate(agent[0], agent[1], agent[2], agent[3]))
            agent.fitness = trialeval
            #      agent.fitness =curreval
            if ((trialeval < curreval) and (trialeval >= 0)):
                # selection -> trialvector is better than original vector
                agent = trialvec
                agent.fitness = trialeval
                print(agent.fitness)


        hof.update(pop1)
        print("halloffame")
        bestid = hof[0]
        print(hof)
        print(toolbox.evaluate(bestid[0], bestid[1], bestid[2], bestid[3]))

        #  history.update(pop1)

        # print(generation)
        generation = generation + 1

    ##extract best individual from the hall of fame
    bestid = hof[0]
    ##extract parameters from individual
    a = ((bestid[0]))
    Rs = ((bestid[1]))
    Rp = ((bestid[2]))
    #    print("Io")
    io = ((bestid[3]))
    #    print(io)
    #    print("RS")
    #    print(Rs)
    #    print("Rp")
    #    print(Rp)
    #    print("a")
    #    print(a)
    #    print("evaluation function")
    #    print(toolbox.evaluate(a, Rs, Rp, io))
    I = Symbol('I', real=True)
    r = (1.0 / (a * Vt))
    # Solve to ensure that Imp is retrieved when Vmp is provided
    print("solving start")
    ## solving equation 3
    #  eqn = Eq(Isc-io*(((sympy.exp(r*(Vmp + (I * Rs))))) - 1)-((Vmp+(I*Rs))/Rp ) - I)
    eqn = Eq(Isc - io * (((exp((float((r * Vmp)) + float((r * (Rs))) * I)))) - 1) - ((Vmp + (I * Rs)) / Rp) - I)
    # t = solve(eqn,I)
    print("solving done")
    # print(t)




main()
```

there's this portion of code right here : 

```
trialvec = toolbox.mate(mutant1, mutant)
trialvec = cxPenalty(trialvec)
trialeval = (toolbox.evaluate(trialvec[0], trialvec[1], trialvec[2], trialvec[3]))
curreval = (toolbox.evaluate(agent[0], agent[1], agent[2], agent[3]))

agent.fitness =curreval
```

for some reason I can't add the fitness value to the agent.fitness, as it returns the following error:

 File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle BigFloat objects

Although if I do this

agent = trialvec
and then 
agent.fitness =curreval

It works without an issue,which is weird as curreval is still a bigfloat and I can't see any difference between the trial vector and the individual. I'm trying to add the fitness values so that the halloffame works correctly, because at the moment it doesn't seem to be returning the individual with the  minimum fitness.

My apologies if this is a very basic question, still learning this side.

Thanks in advance for any help!

**Comment by fmder** [comment]
First you should always replace the fitness.values.

The full stack trace might be of better help.

**Comment by Ian-Re** [comment]
Hi @fmder ,

thank you for the quick response.

I'm assuming this is what you want: 

Traceback (most recent call last):
  File "/home/con3/PycharmProjects/DE/diff.py", line 170, in <module>
    main()
  File "/home/con3/PycharmProjects/DE/diff.py", line 110, in main
    a, b, c = [toolbox.clone(ind) for ind in toolbox.select(pop1)]
  File "/home/con3/PycharmProjects/DE/diff.py", line 110, in <listcomp>
    a, b, c = [toolbox.clone(ind) for ind in toolbox.select(pop1)]
  File "/usr/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/home/con3/.local/lib/python3.6/site-packages/deap/creator.py", line 88, in __deepcopy__
    copy_.__dict__.update(copy.deepcopy(self.__dict__, memo))
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle BigFloat objects


My plan on the replacement of fitness values in the code was this:
```

            agent.fitness = curreval
            #      agent.fitness =curreval
            if ((trialeval < curreval) and (trialeval >= 0)):
                # selection -> trialvector is better than original vector
                agent = trialvec
                agent.fitness = trialeval
                print(agent.fitness)
```

So firstly I assume the agent is the better candidate and add its fitness value using agent.fitness, then i check whether the trial vector is better, if it is, I replace both the agent and it's fitness value with the trial vector and the trial vectors fitness value. This happens on the evaluation of each individual.

**Comment by Ian-Re** [comment]
Using mpmath instead of bigfloat and rewriting the code like this seems to solve this:

```
from mpmath import mp

def eval(a, Rs, Rp, Io):
    r = (1 / (a * Vt))
    Gp = (1 / Rp)
    preex = round((r*(Vmp + (Imp * Rs))), 5)
    expo = mp.exp(preex)
    Jnum = ((Io) * (r) * expo - (Gp))
    Jden = (1 + ((Io) * (r) * (Rs) * expo) + (Gp * Rs))
    J = Jnum / Jden
    return J


######################

            if(curreval >= 0):
                agent.fitness = curreval 
                state.append(curreval)
            if ((trialeval < curreval) and (trialeval >= 0)):
                #selection -> trialvector is better than original vector
                agent = trialvec
                agent.fitness = trialeval
                state.append(trialeval)
```
