### ISSUE TITLE
Documentation example raises error

### ISSUE THREAD

**Issue by imariasantos** [DEAP/deap#427]
The snippet at https://deap.readthedocs.io/en/master/tutorials/basic/part2.html#using-the-tools returns `NameError: name 'pop' is not defined` in both Python 2 and 3.

```
>>> for g in range(NGEN):
...     offspring = toolbox.select(pop, len(pop))
...     offspring = map(toolbox.clone, offspring)
...     for child1, child2 in zip(offspring[::2], offspring[1::2]):
...         if random.random() < CXPB:
...             toolbox.mate(child1, child2)
...             del child1.fitness.values
...             del child2.fitness.values
...     for mutant in offspring:
...         if random.random() < MUTPB:
...             toolbox.mutate(mutant)
...             del mutant.fitness.values
...     invalid_ind = [ind for ind in offspring if not ind.fitness.valid]
...     fitnesses = toolbox.map(toolbox.evaluate, invalid_ind)
...     for ind, fit in zip(invalid_ind, fitnesses):
...         ind.fitness.values = fit
...     pop[:] = offspring
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'pop' is not defined
```

**Comment by MatteoCass** [comment]
I think you could look at the full example under "Algorithms" here: https://deap.readthedocs.io/en/master/overview.html
It will solve the problem you faced with "pop". Though it throws another error at the line 
`for child1, child2 in zip(offspring[::2], offspring[1::2]):
    toolbox.mate(child1, child2)
    del child1.fitness.values
    del child2.fitness.values
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
TypeError: 'map' object is not subscriptable`
