### ISSUE TITLE
xrange not defined in Python3.8

### ISSUE THREAD

**Issue by kaurao** [DEAP/deap#499]
Traceback (most recent call last):
  File "metric_learn.py", line 140, in <module>
    algorithms.eaSimple(pop, toolbox, 0.7, 0.2, 40, stats=stats, halloffame=hof)
  File "/data/project/fingerprint/code/metric_learning/venv/lib/python3.8/site-packages/deap/algorithms.py", line 168, in eaSimple
    offspring = varAnd(offspring, toolbox, cxpb, mutpb)
  File "/data/project/fingerprint/code/metric_learning/venv/lib/python3.8/site-packages/deap/algorithms.py", line 73, in varAnd
    offspring[i - 1], offspring[i] = toolbox.mate(offspring[i - 1],
  File "metric_learn.py", line 47, in wrapper
    for i in xrange(len(child)):
NameError: name 'xrange' is not defined

**Comment by kaurao** [comment]
done in error, it was in my own code!

**Comment by krishna-praveen** [comment]
What was the error? I am getting same error as 'xrange' is not defined.

**Comment by kaurao** [comment]
> 
> 
> What was the error? I am getting same error as 'xrange' is not defined.

The difference is Python 2 versus Python 3.

https://stackoverflow.com/questions/17192158/nameerror-global-name-xrange-is-not-defined-in-python-3

**Comment by fmder** [comment]
Examples are still Python 2 (sadly). You have to convert them with 2to3 or manually.
