### ISSUE TITLE
Example cma_minfct.py doesn't work with the logger enabled

### ISSUE THREAD

**Issue by bje-** [DEAP/deap#504]
When I uncomment out the `logger =` line, I get:

```
Traceback (most recent call last):
  File "cma_minfct.py", line 60, in <module>
    main()
  File "cma_minfct.py", line 51, in main
    logger = tools.EvolutionLogger(stats.functions.keys())
AttributeError: module 'deap.tools' has no attribute 'EvolutionLogger'
```

**Comment by fmder** [comment]
You are right, this line is an artifact of the past. I'm not even sure EvolutionLogger ever made it to a release.

Thanks for reporting.
