### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by nbro** [DEAP/deap#537]
I forked deap, cloned my fork and I tried to install the cloned version with `python setup.py install` inside a conda environment with Python 3.7. Then I try to run an example, even with just the import `from deap import base`, and I get the error

```
Traceback (most recent call last):
  File "/path/deap/example.py", line 3, in <module>
    from deap import base
  File "/path/deap/deap/base.py", line 193
    raise TypeError, ("Both weights and assigned values must be a "
                   ^
SyntaxError: invalid syntax
```

This is, of course, due to the fact that deap is not written for 3.7, as can be seen [here](https://github.com/DEAP/deap/blob/master/deap/base.py#L193), where that syntax is not supported in Python 3.7. As far as I understand, [deap uses the option `use_2to3=True` to convert this code written in Python 2 to Python 3 during the installation](https://github.com/DEAP/deap/blob/master/setup.py#L90), however, either if I install my cloned version with `python setup.py install` or `pip install -e .`, this option is not applied, so I cannot run the code in editable mode.

So, what's your approach to edit/develop deap in Python 3? I would like to change something in deap (i.e. add a feature), but I'm not sure what's the right approach here.

**Comment by fmder** [comment]
unfortunately -e does not support 2to3.

**Comment by nbro** [comment]
@fmder So, what's your approach to developing Deap in Python 3?

**Comment by microprediction** [comment]
I'm also having problems caused by 2to3.

**Comment by fmder** [comment]
I'm rewriting the whole thin gin python3, but that take way more time than I have 😞

**Comment by meghkc** [comment]
I am having exactly same problem. even I am using python 3.10
what should we do to get rid pf this problem?
I was having problem with installing deap 1.3.1 initially but it solved after demoting the setup tools version to 58.0.0
pip is 22.1.1 version
![deap library](https://user-images.githubusercontent.com/97197361/172028295-f58b3389-6051-4143-9490-f1d015f8fa71.PNG)

**Comment by julien-blanchon** [comment]
+1
