### ISSUE TITLE
Spambase example broken

### ISSUE THREAD

**Issue by akiross** [DEAP/deap#61]
I cannot make spambase example run correctly. I get the following error (using version 1.0 installed from pip, with python3).

	Traceback (most recent call last):
	  File "/usr/lib64/python3.4/random.py", line 253, in choice
		i = self._randbelow(len(seq))
	  File "/usr/lib64/python3.4/random.py", line 230, in _randbelow
		r = getrandbits(k)          # 0 <= r < 2**k
	ValueError: number of bits must be greater than zero

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/home/username/.local/lib/python3.4/site-packages/deap/gp.py", line 584, in generate
		prim = random.choice(pset.primitives[type_])
	  File "/usr/lib64/python3.4/random.py", line 255, in choice
		raise IndexError('Cannot choose from an empty sequence')
	IndexError: Cannot choose from an empty sequence

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "spamthing.py", line 110, in <module>
		main()
	  File "spamthing.py", line 97, in main
		pop = toolbox.population(n=100)
	  File "/home/username/.local/lib/python3.4/site-packages/deap/tools/init.py", line 23, in initRepeat
		return container(func() for _ in range(n))
	  File "/home/username/.local/lib/python3.4/site-packages/deap/tools/init.py", line 23, in <genexpr>
		return container(func() for _ in range(n))
	  File "/home/username/.local/lib/python3.4/site-packages/deap/tools/init.py", line 49, in initIterate
		return container(generator())
	  File "/home/username/.local/lib/python3.4/site-packages/deap/gp.py", line 539, in genHalfAndHalf
		return method(pset, min_, max_, type_)
	  File "/home/username/.local/lib/python3.4/site-packages/deap/gp.py", line 524, in genGrow
		return generate(pset, min_, max_, condition, type_)
	  File "/home/username/.local/lib/python3.4/site-packages/deap/gp.py", line 589, in generate
		"none available." % (type_,)).with_traceback(traceback)
	  File "/home/username/.local/lib/python3.4/site-packages/deap/gp.py", line 584, in generate
		prim = random.choice(pset.primitives[type_])
	  File "/usr/lib64/python3.4/random.py", line 255, in choice
		raise IndexError('Cannot choose from an empty sequence')
	IndexError: The gp.generate function tried to add a primitive of type '<class 'object'>', but there is none available.

**Comment by cmd-ntrf** [comment]
Each night, the examples are run against different version of Python. You can see the results here for spambase: http://deap.gel.ulaval.ca/speed/example.html?name=gp/spambase&branch=1.0.x

Since the traceback mentions "spamthing.py", I am guessing you have somehow modified the code of the example. This is totally fine, but I am pretty sure that your modifications are to blame for the errors, not the example itself, and unless I see that code, I cannot help you.

**Comment by akiross** [comment]
That's not the case, `spamthing.py` has that name just because I copied-pasted into a new file the same content, which _was not modified_. Same things happen with code cloned from git.

Anyway, the problem seems to be fixed by setting the argument `type_` in the generator functions, for example changing from

    toolbox.register("expr", gp.genHalfAndHalf, pset=pset, min_=1, max_=2)

to

    toolbox.register("expr", gp.genHalfAndHalf, pset=pset, min_=1, max_=2, type_=float)

and the same when registering `expr_mut`.

**Comment by fmder** [comment]
Where did you copied the example from? Make sure it is from branch 1.0 of
the git repo? Any other version might cause trouble.

2015-03-18 16:03 GMT-04:00 akiross <notifications@github.com>:

**Comment by akiross** [comment]
@fmder you are right, I pasted the copy from master branch; still, I just tested with code from [branch 1.0.x](https://raw.githubusercontent.com/DEAP/deap/1.0.x/examples/gp/spambase.py) and the error is the same.

**Comment by cmd-ntrf** [comment]
Sorry for the shitty attitude. The bug is fixed since last year. https://github.com/DEAP/deap/commit/77396f4000d73bf5c28dd56c0f900946bccedca9

However, it appears that we have forgot to release it. I will try to bundle a new release by the end of the week, 1.0.2 is way overdue. In the meantime, you can install the 1.0.x branch.
https://github.com/DEAP/deap/tree/1.0.x

**Comment by akiross** [comment]
lol don't worry, it's understandable. Good to know that's fixed, I'll try using the new code instead of the pip version. Thanks!
