### ISSUE TITLE
Cannot pass many inputs to compiled tree

### ISSUE THREAD

**Issue by ibell** [DEAP/deap#69]
I am developing a multi-dimensional symbolic regression program, and it seems to work pretty much fine when I have three input variables, but when I have 10 input variables (plus some constants to be solved for), it dies (see below).  Is there a limit to how many inputs can be set using  ``pset.renameArguments(ARG0='x_0')``?

```
Traceback (most recent call last):
  File "pysr.py", line 235, in <module>
    main(None, xvecs, yvec)
  File "pysr.py", line 183, in main
    halloffame=hof, verbose=True)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\deap\algorithms.py", line 147, in eaSimple
    fitnesses = toolbox.map(toolbox.evaluate, invalid_ind)
  File "pysr.py", line 152, in evalInvSqrt
    disp=False)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\scipy\optimize\optimize.py", line 374, in fmin
    res = _minimize_neldermead(func, x0, args, callback=callback, **opts)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\scipy\optimize\optimize.py", line 433, in _minimize_neldermead
    fsim[0] = func(x0)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\scipy\optimize\optimize.py", line 282, in function_wrapper
    return function(*(wrapper_args + args))
  File "pysr.py", line 113, in evalParams
    errsum = math.fsum(sqerrors)
  File "pysr.py", line 110, in <genexpr>
    sqerrors = ((func(*(list(IO[1::]) + list(params))) - IO[0])**2 for IO in zip(yvec, *xvecs))
TypeError: <lambda>() takes exactly 5 arguments (10 given)
```

**Comment by ibell** [comment]
False alarm - the arity was set incorrectly in ``gp.PrimitiveSet()`` in my code.  It should have been larger
