### ISSUE TITLE
DEAP + Multiprocessing/Pool

### ISSUE THREAD

**Issue by yhamadi75** [DEAP/deap#92]
I have a program which uses DEAP and Python's Pool of worker for parallel evaluation of fitnesses. Roughly, I create objects then,

        nbCPU = multiprocessing.cpu_count()
        chunk = len(population) / nbCPU
        print('workers=', nbCPU, 'chunksize=', chunk)
        pool = multiprocessing.Pool(nbCPU)
        toolbox.register("map", pool.map, chunksize = chunk)

This is working finely on MAX OS X. However the same code on windows does not run:

Process PoolWorker-4:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
Process PoolWorker-3:
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 102, in worker
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 102, in worker
    task = get()
  File "C:\Python27\lib\multiprocessing\queues.py", line 376, in get
    return recv()
    task = get()
  File "C:\Python27\lib\multiprocessing\queues.py", line 376, in get
AttributeError: 'module' object has no attribute 'Individual'
    return recv()
AttributeError: 'module' object has no attribute 'Individual'
Process PoolWorker-2:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap

I do understand that the problem comes from the way Windows manages processes. Looking around, I found this thread, https://github.com/DEAP/deap/issues/57. It makes reference to a work-in-progress version of DEAP (deap-1) which should run without the previous problem on windows.

Can I expect integration of this new version in the master branch soon? Is there another work around?

Any help on this would be very much appreciated.

-  y

**Comment by fmder** [comment]
Multiprocessing is fully supported on OSX and Windows. See the full example in the deap/examples/ga directory. With the very small code snippet you gave I would say that the individuals need to be created at the global scope of your code and that the pool should be created in the main section. These are the two most common mistakes.

To ask questions about deap please use the deap-users google group.
